// ReefGuard-Q desktop-first design tokens (v2), extracted verbatim from
// reefguard-frontend-design-v2/shared/tailwind-tokens.js. This REPLACES the
// earlier mobile-first token set (different palette, different roundedness
// philosophy -- pill-shaped everything vs. the earlier sharp/minimal look),
// per the v2 design brief's explicit "replace, not merge" instruction.
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-surface': '#dfe2ef',
        'tertiary-fixed-dim': '#ffb2b7',
        'on-primary-fixed': '#002019',
        background: '#0f131c',
        'on-secondary-fixed': '#00201d',
        'surface-container-lowest': '#0a0e17',
        outline: '#84948e',
        'secondary-fixed-dim': '#6bd8cb',
        'surface-container': '#1c1f29',
        'surface-container-high': '#262a34',
        'on-primary-container': '#00614f',
        surface: '#0f131c',
        'surface-bright': '#353943',
        'primary-fixed': '#42fdd5',
        'secondary-container': '#29a195',
        'on-surface-variant': '#b9cac3',
        'on-primary-fixed-variant': '#005142',
        'tertiary-fixed': '#ffdadb',
        'primary-container': '#00e5be',
        'inverse-primary': '#006b58',
        'outline-variant': '#3b4a45',
        'surface-tint': '#00e0ba',
        'on-tertiary-container': '#ad0033',
        'inverse-surface': '#dfe2ef',
        'on-secondary': '#003732',
        'tertiary-container': '#ffb9bd',
        primary: '#6fffdb',
        'error-container': '#93000a',
        'secondary-fixed': '#89f5e7',
        'surface-variant': '#31353f',
        'surface-container-low': '#181b25',
        'on-primary': '#00382d',
        'surface-container-highest': '#31353f',
        'primary-fixed-dim': '#00e0ba',
        'on-tertiary-fixed-variant': '#92002a',
        'on-error-container': '#ffdad6',
        'on-error': '#690005',
        'on-background': '#dfe2ef',
        'on-secondary-fixed-variant': '#005049',
        'inverse-on-surface': '#2c303a',
        'on-tertiary': '#67001b',
        error: '#ffb4ab',
        'surface-dim': '#0f131c',
        secondary: '#6bd8cb',
        'on-tertiary-fixed': '#40000d',
        tertiary: '#ffe0e1',
        'on-secondary-container': '#00302b',
      },
      borderRadius: { DEFAULT: '1rem', lg: '2rem', xl: '3rem', full: '9999px' },
      spacing: {
        'space-xl': '2rem',
        'margin-desktop': '3rem',
        'space-2xs': '0.25rem',
        'space-3xl': '4.5rem',
        'max-content-width': '1440px',
        'space-lg': '1.5rem',
        'space-2xl': '3rem',
        'space-sm': '0.75rem',
        'gutter-desktop': '1.5rem',
        'space-xs': '0.5rem',
        'space-md': '1rem',
      },
      fontFamily: {
        'body-md': ['Inter'],
        'telemetry-sm': ['JetBrains Mono'],
        'label-md': ['Inter'],
        'headline-md': ['Playfair Display'],
        'telemetry-md': ['JetBrains Mono'],
        'display-xl-mobile': ['Playfair Display'],
        'body-sm': ['Inter'],
        'headline-sm': ['Playfair Display'],
        'label-lg': ['Inter'],
        'headline-lg-mobile': ['Playfair Display'],
        'telemetry-lg': ['JetBrains Mono'],
        'display-xl': ['Playfair Display'],
        'body-lg': ['Inter'],
        'headline-lg': ['Playfair Display'],
      },
      fontSize: {
        'body-md': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'telemetry-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'telemetry-md': ['14px', { lineHeight: '20px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'display-xl-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '500' }],
        'telemetry-lg': ['20px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '500' }],
        'display-xl': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '500' }],
      },
    },
  },
};
